export const COMMUNICATIONS_UI_ENABLED =
  import.meta.env.VITE_COMMUNICATIONS_ENABLED === "true";

export const COMMUNICATION_DOCUMENTS_UI_ENABLED =
  COMMUNICATIONS_UI_ENABLED
  && import.meta.env.VITE_COMMUNICATION_DOCUMENTS_ENABLED === "true";

export const COMMUNICATION_PUBLICATION_UI_ENABLED =
  COMMUNICATIONS_UI_ENABLED
  && import.meta.env.VITE_COMMUNICATION_PUBLICATION_ENABLED === "true";
